module.exports = {
    url: "https://accesscity.gr",
    blog: {
        eyebrowEl: "Νέα & Ανακοινώσεις",
        eyebrowEn: "News & Announcements",
        titleEl: "Τι συμβαίνει στο AccessCity",
        titleEn: "What's happening at AccessCity",
        leadEl:
            "Ενημερωτικές αναρτήσεις για τη δράση μας, τις συνεργασίες μας και τις εξελίξεις στον χώρο της αστικής προσβασιμότητας.",
        leadEn:
            "Updates about our work, partnerships, and developments in urban accessibility.",
    },
    ui: {
        skipEl: "Μετάβαση στο περιεχόμενο",
        skipEn: "Skip to content",
        aboutEl: "Τι είναι",
        aboutEn: "About",
        howEl: "Πώς λειτουργεί",
        howEn: "How it works",
        citiesEl: "Για δήμους",
        citiesEn: "For cities",
        getInvolvedEl: "Συμμετοχή",
        getInvolvedEn: "Get involved",
        newsEl: "Νέα",
        newsEn: "News",
        contactEl: "Επικοινώνησε",
        contactEn: "Contact",
        footerAboutEl: "Σχετικά",
        footerAboutEn: "About",
        footerProcessEl: "Διαδικασία",
        footerProcessEn: "Process",
        footerContactEl: "Επικοινωνία",
        footerContactEn: "Contact",
        readMoreEl: "Διάβασε περισσότερα →",
        readMoreEn: "Read more →",
        backToNewsEl: "← Πίσω στα νέα",
        backToNewsEn: "← Back to news",
    },
};